name: Model train Workflow

on:
  workflow_dispatch:  # manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository # checkout the code
      uses: actions/checkout@v4

    - name: Set up Python # setup python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.12'

    - name: Install dependencies # install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script # run the training script
      run: |
        python train.py

    - name: Upload artifacts # upload the output
      uses: actions/upload-artifact@v4
      with:
        name: model-output
        path: out/
